// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gelwmgayqxwqyfazrcrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlbHdtZ2F5cXh3cXlmYXpyY3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTM2NTAsImV4cCI6MjA2MTY4OTY1MH0.tTiV-0efbStPxZgczaGMy7GGWhKZ_b7swwPzKO5_jwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);